export default [
  {
    nome: "Cheese burguer",
    tipo: "hamburguer",
    ingredientes: [
      "Pão da casa",
      "hambúrguer",
      "queijo mussarela",
      "molho da casa",
      "salada",
    ],
    preco: 12,
    img: "assets/cheeseburguer.svg",
    alt: "imagem do cheeseburguer",
  },
  {
    nome: "Bacon burguer",
    tipo: "hamburguer",
    ingredientes: [
      "Pão da casa",
      "hambúrguer",
      "queijo mussarela",
      "bacon em tiras",
      "cebola caramelizada",
      "molho da casa",
    ],
    preco: 16,
    img: "assets/baconburguer.svg",
    alt: "imagem do bacon burguer",
  },
  {
    nome: "Duplo cheddar",
    tipo: "hamburguer",
    ingredientes: [
      "Pão da casa",
      "dois hambúrgueres",
      "queijo cheddar",
      "salada",
      "molho barbecue",
    ],
    preco: 20,
    img: "assets/duplocheddar.svg",
    alt: "imagem do duplo cheddar burguer",
  },
  {
    nome: "Onion rings cheddar burguer",
    tipo: "hamburguer",
    ingredientes: [
      "Pão da casa",
      "hambúrguer",
      "queijo cheddar",
      "onion rings",
      "cebola caramelizada",
      "cebola roxa",
    ],
    preco: 20,
    img: "assets/onionburguer.svg",
    alt: "imagem do onion rings cheddar burguer",
  },
  {
    nome: "Agua com/sem gas",
    tipo: "bebida",
    preco: 3,
    img: "assets/agua.svg",
    alt: "imagem da água",
  },
  {
    nome: "Coca cola lata",
    tipo: "bebida",
    preco: 5,
    img: "assets/cocacola.svg",
    alt: "imagem da coca-cola",
  },
  {
    nome: "Guaraná lata",
    tipo: "bebida",
    preco: 5,
    img: "assets/guarana.svg",
    alt: "imagem do guaraná",
  },
  {
    nome: "Batata frita",
    tipo: "acompanhamento",
    preco: 10,
    img: "assets/batata.svg",
    alt: "imagem da batata frita",
  },
  {
    nome: "Batata frita c/ cheddar e bacon",
    tipo: "acompanhamento",
    preco: 15,
    img: "assets/batata-cheddar-bacon.svg",
    alt: "imagem da batata frita com cheddar e bacon",
  },
];
